name: Laravel CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Best-practices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Create environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Run Pint
        run: ./vendor/bin/pint --test
